quotes_app/urls.py
from django.urls import path

from . import views

app_name = "quotes_app"

urlpatterns = [
    path("", views.QuotesListView.as_view(), name="index"),
    path("authors/<pk>", views.AuthorDetailView.as_view(), name="specific_author"),
    path("authors/", views.AuthorsListView.as_view(), name="all_authors"),
    path("tags/", views.TagsListView.as_view(), name="all_tags"),
    path(
        "tags/<str:tagname>", views.QuotesByTagListView.as_view(), name="specific_tag"
    ),
    path("sync_quotes/", views.sync, name="sync_quotes"),
]

quotes_proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("quotes_app.urls")),
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.sign_in, name="login"),
    path('password_reset/', views.EmailOnlyPasswordResetView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("signout/", views.SignOutView.as_view(), name="sign_out"),
    path("add-quote/", views.QuoteCreateView.as_view(), name="add_quote"),
    path("add-author/", views.AuthorCreateView.as_view(), name="add_author"),
    path("add-tag/", views.TagCreateView.as_view(), name="add_tag"),
    path("edit-quote/<pk>", views.QuoteUpdateView.as_view(), name="edit_quote"),
    path("delete-quote/<pk>", views.QuoteDeleteView.as_view(), name="delete_quote"),
    path("edit-author/<pk>", views.AuthorUpdateView.as_view(), name="edit_author"),
    path("delete-author/<pk>", views.AuthorDeleteView.as_view(), name="delete_author"),
    path("edit-tag/<pk>", views.TagUpdateView.as_view(), name="edit_tag"),
    path("delete-tag/<pk>", views.TagDeleteView.as_view(), name="delete_tag"),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm,
                                       UsernameField, PasswordResetForm)
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from quotes_app.models import Author, Quote, Tag  # noqa

form_style = "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"


class RegisterForm(UserCreationForm):
    username = forms.EmailField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": form_style}),
    )
    password1 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(attrs={"class": form_style}),
    )
    password2 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(attrs={"class": form_style}),
    )

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={"autofocus": True, "class": form_style})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "class": form_style}
        ),
    )

    class Meta:
        model = User
        fields = ["username", "password"]


form_field_style = "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-600 dark:focus:ring-blue-500 dark:focus:border-blue-500"
form_textfield_style = "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"


class AddQuoteForm(forms.ModelForm):
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        widget=forms.Select(attrs={"class": form_field_style}),
    )
    quote = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={"class": form_textfield_style, "rows": 4})
        # Adjust cols and rows as needed "cols": 80
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.SelectMultiple(attrs={"class": form_field_style}),
    )

    class Meta:
        model = Quote
        fields = ["author", "quote", "tags"]


class AddAuthorForm(forms.ModelForm):
    fullname = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(attrs={"class": form_field_style}),
    )
    born_date = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": form_field_style}),
    )
    born_location = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": form_field_style}),
    )
    description = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={"class": form_textfield_style, "rows": 4}),
    )

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class AddTagForm(forms.ModelForm):
    word = forms.CharField(
        max_length=35,
        required=True,
        widget=forms.TextInput(attrs={"class": form_style}),
    )

    class Meta:
        model = Tag
        fields = ["word"]

class ResetForm(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.TextInput(attrs={"autofocus": True, "class": form_style})
    )

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, ListView, UpdateView,
                                  View)
from quotes_app.models import Author, Quote, Tag  # noqa

from .forms import (AddAuthorForm, AddQuoteForm, AddTagForm, LoginForm,
                    RegisterForm, ResetForm)


def register(request):
    """
    The register function is responsible for handling the registration of new users.
    It first checks if the user is already authenticated, and if so redirects them to the index page.
    If not, it then checks whether or not a POST request has been made (i.e., whether or not a form has been submitted).
    If so, it creates an instance of RegisterForm with that data and validates it; if valid, saves the form's data as a new User object in our database and redirects to login page; otherwise renders register template with invalid form instance passed as context. If no POST request was made (i.e.,
    
    :param request: Get the request object
    :return: The rendered register
    :doc-author: Trelent
    """
    if request.user.is_authenticated:
        return redirect(to="quotes_app:index")

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="users:login")
        else:
            return render(request, "users/register.html", context={"form": form})

    return render(request, "users/register.html", context={"form": RegisterForm()})


def sign_in(request):
    """
    The sign_in function is a view that allows users to sign in.
        If the user is already signed in, they are redirected to the index page.
        If the request method is POST, then we authenticate and log them in if their username and password match.
        Otherwise, we redirect them back to login with an error message.
    
    :param request: Pass the request object to the view
    :return: A redirect to the index page if the user is already authenticated
    :doc-author: Trelent
    """
    if request.user.is_authenticated:
        return redirect(to="quotes_app:index")
    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")
        login(request, user)
        return redirect(to="users:dashboard")
    return render(request, "users/login.html", context={"form": LoginForm()})


class EmailOnlyPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('users:login')



# @login_required
@method_decorator(login_required, name="dispatch")
class DashboardView(ListView):
    model = Quote
    template_name = "users/dashboard.html"
    success_url = reverse_lazy("dashboard")
    context_object_name = "quotes"
    paginate_by = 2

    # ordering = ["date_created"]

    def get_queryset(self):
        """
        The get_queryset function is used to filter the queryset of objects that are displayed in the view.
        In this case, we're filtering it so that only objects created by the current user are shown.
        
        :param self: Represent the instance of the class
        :return: A queryset of all the objects created by a user
        :doc-author: Trelent
        """
        queryset = super(DashboardView, self).get_queryset()
        return queryset.filter(created_by=self.request.user).order_by("date_created")

    def get_context_data(self, **kwargs):
        """
        The get_context_data function is a method that Django calls when rendering the template.
        It allows you to add additional context variables to the template, which are then available in 
        the rendered HTML. In this case, we're adding three variables: quotes, authors and tags.
        
        :param self: Represent the instance of the class
        :param **kwargs: Pass keyworded, variable-length argument list
        :return: A dictionary of data that is used to render the template
        :doc-author: Trelent
        """
        context = super(DashboardView, self).get_context_data(**kwargs)
        quotes = Quote.objects.filter(created_by=self.request.user).order_by(
            "-date_created"
        )
        authors = Author.objects.filter(created_by=self.request.user).order_by(
            "-date_created"
        )
        tags = Tag.objects.filter(created_by=self.request.user).order_by(
            "-date_created"
        )
        paginator_quotes = Paginator(quotes, 4)
        # paginator_authors = Paginator(authors, 4)
        context["quotes"] = paginator_quotes
        context["authors"] = authors
        context["tags"] = tags
        return context


@method_decorator(login_required, name="dispatch")
class SignOutView(View):
    def get(self, request):
        logout(request)
        return redirect("quotes_app:index")


@method_decorator(login_required, name="dispatch")
class QuoteCreateView(CreateView):
    model = Quote
    form_class = AddQuoteForm
    template_name = "users/add_quote.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class AuthorCreateView(CreateView):
    model = Author
    form_class = AddAuthorForm
    template_name = "users/add_author.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class TagCreateView(CreateView):
    model = Tag
    form_class = AddTagForm
    template_name = "users/add_tag.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class QuoteUpdateView(UpdateView):
    model = Quote
    form_class = AddQuoteForm
    template_name = "users/add_quote.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to edit this Quote.")
        return obj


@method_decorator(login_required, name="dispatch")
class QuoteDeleteView(DeleteView):
    model = Quote
    template_name = "users/delete_confirm_quote.html"
    success_url = reverse_lazy("users:dashboard")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to delete this Quote.")
        return obj


@method_decorator(login_required, name="dispatch")
class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AddAuthorForm
    template_name = "users/add_author.html"
    success_url = reverse_lazy("users:dashboard")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to edit this Author.")
        return obj


@method_decorator(login_required, name="dispatch")
class AuthorDeleteView(DeleteView):
    model = Author
    template_name = "users/delete_confirm_author.html"
    success_url = reverse_lazy("users:dashboard")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to delete this Author.")
        return obj


@method_decorator(login_required, name="dispatch")
class TagUpdateView(UpdateView):
    model = Tag
    template_name = "users/add_tag.html"
    success_url = reverse_lazy("users:dashboard")
    form_class = AddTagForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to edit this Author.")
        return obj


@method_decorator(login_required, name="dispatch")
class TagDeleteView(DeleteView):
    model = Tag
    template_name = "users/delete_confirm_tag.html"
    success_url = reverse_lazy("users:dashboard")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by != self.request.user:
            raise Http404("You are not allowed to delete this Author.")

users/templates/users/add_author.html
{% extends "theme/base.html" %}

{% block content %}

<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Add Author</h1>

</div>

<form method="post">
{% csrf_token %}
    fullname:
    {{ form.fullname }}
    born_date:
    {{ form.born_date }}
    born_location:
    {{ form.born_location }}
    description:
    {{ form.description }}
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Submit
    </button>
</form>


{% endblock %}

users/templates/users/add_quote.html
{% extends "theme/base.html" %}

{% block content %}

<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Add Quote</h1>

</div>

<form method="post">
    {% csrf_token %}
    {{ form.author }}
    {{ form.quote }}
    {{ form.tags }}
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Submit
    </button>
</form>


{% endblock %}

users/templates/users/dashboard.html
{% extends "theme/base.html" %}

{% block content %}
<div class="grid grid-cols-2">

    <div class="grid grid-rows-1 ">
        <p class="m-10">Logged in as: {% if user.is_authenticated %}{{ user.username }}{% endif %}</p>
    </div>


    <div class="grid grid-rows-1 justify-items-end">
        <a href="{% url 'quotes_app:sync_quotes' %}"
           class="m-10 p-2 text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Update
            quotes</a>
    </div>
</div>

<div class="flex flex-wrap grid-flow-col  justify-center gap-4">
    <div class="grid flex-wrap pt-10 justify-items-center pb-3">
        <h1 class="text-5xl mb-5 text-center">My quotes:</h1>
        <hr class="m-10">
        {% include "theme/quote_card.html" %}


        <div class="grid grid-cols-1 justify-items-center flex-row">
            <!-- Previous Button -->
            <div class="grid">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}"
                   class="items-center justify-center px-20 h-10 text-base font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    <svg class="w-3.5 h-3.5 me-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         fill="none" viewBox="0 0 14 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M13 5H1m0 0 4 4M1 5l4-4"/>
                    </svg>
                    Previous
                </a>
                {% endif %}
            </div>
            <div class="grid">
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}"
                   class="items-center justify-center px-20 h-10 text-base font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    Next
                    <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         fill="none" viewBox="0 0 14 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M1 5h12m0 0L9 1m4 4L9 9"/>
                    </svg>
                </a>
                {% endif %}
            </div>

        </div>

    </div>

    <div class="flex-wrap grid">


        <!--authors section-->
        <div>
            <div class="pt-10 pb-3">
                <h1 class="text-5xl text-center mb-5">My Authors:</h1>
                <hr class="m-10">
            </div>
            <div class="pb-2 p-5">

                {% for author in authors %}
                <div class="p-2">
                    <a href="{% url 'quotes_app:specific_author' author.id %}"
                       class="font-normal text-gray-700 dark:text-gray-600 hover:text-blue-500">{{ author.fullname }}</a>
                </div>
                {% endfor %}
            </div>
        </div>


        <!--tags section-->
        <div class="pt-10 pb-3">
            <h1 class="text-5xl text-center mb-5">My Tags:</h1>
            <hr class="m-10">
        </div>

        <div class="grid pb-5">
            {% for tag in tags %}
            <div class="grid grid-cols-2 p-2 ">
                <div class="gird">
                    <a href="{% url 'quotes_app:specific_tag' tag %}"
                       class="font-normal text-gray-700 dark:text-gray-600 hover:text-blue-500">#{{ tag.word }}</a>
                </div>
                <div class="flex font-normal text-sm text-gray-700 dark:text-gray-600 place-content-center ">
                    {% if tag.created_by and tag.created_by.id == user.id %}
                    <div class="text-blue-600">
                        <a href="{% url 'users:edit_tag' tag.id %}" class="#">Edit tag</a>
                    </div>
                    <div class="text-red-600">
                        <a href="{% url 'users:delete_tag' tag.id %}">Delete tag</a>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/delete_confirm_author.html
{% extends "theme/base.html" %}

{% block content %}
<p class="">Logged in as: {% if user.is_authenticated %}{{ user.username }}{% endif %}</p>
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Deleting</h1>
    <hr class="m-10">
</div>

<form method="post" action="{% url 'users:delete_author' pk=object.pk %}" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-5">
        <p class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-700">
            Are you sure you want to delete "{{ object }}"?
        </p>
    </div>
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Confirm
    </button>
    <button type="reset" class="text-gray-700 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800">
            Reset
        </button>
</form>

{% include "theme/pagination.html" %}
{% endblock %}

users/templates/users/delete_confirm_quote.html
{% extends "theme/base.html" %}

{% block content %}
<p class="">Logged in as: {% if user.is_authenticated %}{{ user.username }}{% endif %}</p>
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Deleting</h1>
    <hr class="m-10">
</div>

<form method="post" action="{% url 'users:delete_quote' pk=object.pk %}" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-5">
        <p class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-700">
            Are you sure you want to delete "{{ object }}"?
        </p>
    </div>
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Confirm
    </button>
    <button type="reset" class="text-gray-700 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800">
            Reset
        </button>
</form>

{% include "theme/pagination.html" %}
{% endblock %}

users/templates/users/delete_confirm_tag.html
{% extends "theme/base.html" %}

{% block content %}
<p class="">Logged in as: {% if user.is_authenticated %}{{ user.username }}{% endif %}</p>
<div class="grid items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Deleting</h1>
    <hr class="m-10">
</div>

<form method="post" action="{% url 'users:delete_tag' pk=object.pk %}" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-5">
        <p class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-700">
            Are you sure you want to delete "{{ object }}"?
        </p>
    </div>
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Confirm
    </button>
    <button type="reset" class="text-gray-700 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800">
            Reset
        </button>
</form>

{% include "theme/pagination.html" %}
{% endblock %}

users/templates/users/login.html
{% extends "theme/base.html" %}

{% block content %}
<div class="flex items-center justify-center pt-10 pb-3">
    <h1 class="text-5xl mb-5">Login</h1>
</div>
{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<div class="flex">
    <form action="{% url 'users:login' %}" method="post" class="max-w-sm mx-auto mt-10">
        {% csrf_token %}
        <div class="mb-5">
            <label> Email:
                {{ form.username }}
            </label>
        </div>

        <div class="mb-5">
            <label>Password:
                {{ form.password }}
            </label>
            <a class="text-red-500 text-xs" href="{% url 'users:password_reset' %}">reset password</a>
        </div>

        <div class="grid pt-8 items-center space-4">
            <button type="submit" class="m-1 w-15 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 text-white font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
            <!-- <button type="reset" class="m-1 w-15 bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none focus:ring-gray-300 text-gray-800 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-gray-600 dark:hover:bg-gray-400 dark:focus:ring-gray-600">Reset</button> -->
        </div>
    </form>
</div>

{% include "theme/pagination.html" %}


{% endblock %}

users/templates/users/password_reset.html
{% extends "theme/base.html" %}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'users:login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

users/templates/users/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}